# Generated by Django 4.2.5 on 2024-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics')], default='physics', max_length=20),
        ),
    ]
