# Generated by Django 4.2.5 on 2024-03-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_correct_option_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subj',
            field=models.CharField(choices=[('1', 'Physics'), ('2', 'Chemistry'), ('3', 'Maths'), ('4', 'Biology')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='kinematics', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
