# Generated by Django 4.2.5 on 2024-03-23 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_correct_answer_alter_question_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
            preserve_default=False,
        ),
    ]
